version: "3"
services:
  proxy-rank:
    build: .
    image: proxy-mon
    container_name: proxy-dash
    volumes: 
      - /www/proxy-mon:/app
    working_dir: /app
    networks: 
      - default
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
    environment: 
      - PROXY_RANK_MAIL_FROM=${MAIL_FROM:-"Henry TIAN <chariothy@gmail.com>"}
      - PROXY_RANK_MAIL_TO=${MAIL_TO:-"Henry TIAN <chariothy@gmail.com>"}
      - PROXY_RANK_SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - PROXY_RANK_SMTP_PORT=${SMTP_PORT:-25}
      - PROXY_RANK_SMTP_USER=${SMTP_USER:-chariothy@gmail.com}
      - PROXY_RANK_SMTP_PWD=${SMTP_PWD}
    command: python server.py