version: "3"
services:
  proxy-dash:
    build: .
    image: proxy-mon
    container_name: proxy-dash
    volumes: 
      - /www/proxy-mon:/app
    working_dir: /app
    networks: 
      - default
    restart: unless-stopped
    ports: 
      - ${PROXY_MON_PORT:-8050}:8050
    logging:
      options:
        max-size: "10m"
    environment: 
      - ENV=${ENV}
    command: python server.py
  proxy-rank:
    build: .
    image: proxy-mon
    container_name: proxy-rank
    volumes: 
      - /usr/bin/scp:/usr/bin/scp:ro
      - /usr/bin/ssh:/usr/bin/ssh:ro
      - ~/.ssh:/home/${UNAME}/.ssh:ro
      - /www/proxy-mon:/app
    working_dir: /app
    networks: 
      - default
    userns_mode: "host"
    restart: "no"
    logging:
      options:
        max-size: "10m"
    environment: 
      - ENV=${ENV}
      - PROXY_RANK_MAIL_FROM=${MAIL_FROM:-"Henry TIAN <chariothy@gmail.com>"}
      - PROXY_RANK_MAIL_TO=${MAIL_TO:-"Henry TIAN <chariothy@gmail.com>"}
      - PROXY_RANK_SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - PROXY_RANK_SMTP_PORT=${SMTP_PORT:-25}
      - PROXY_RANK_SMTP_USER=${SMTP_USER:-chariothy@gmail.com}
      - PROXY_RANK_SMTP_PWD=${SMTP_PWD}
      - PROXY_RANK_DINGTALK_TOKEN=${DINGTALK_TOKEN}
      - PROXY_RANK_DINGTALK_SECRET=${DINGTALK_SECRET}
    command: python main.py